version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=application
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/:/data
    command: redis-server --appendonly yes

networks:
  default:
    driver: bridge